//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByoBaby.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByoBaby.Security.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for parameter {0} cannot be null or an empty string..
        /// </summary>
        internal static string ArgumentMissing {
            get {
                return ResourceManager.GetString("ArgumentMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only authenticated users can perform this action..
        /// </summary>
        internal static string AuthenticatedUsersOnlyMessage {
            get {
                return ResourceManager.GetString("AuthenticatedUsersOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenication failed. Invalid username and/or password..
        /// </summary>
        internal static string AuthenticationFailedMessage {
            get {
                return ResourceManager.GetString("AuthenticationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between {0} and {1}.
        /// </summary>
        internal static string BetweenDateText {
            get {
                return ResourceManager.GetString("BetweenDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A donation with the id &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string DonationDoesntExistMessage {
            get {
                return ResourceManager.GetString("DonationDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only group administrators can perform this action..
        /// </summary>
        internal static string GroupAdministratorsOnlyMessage {
            get {
                return ResourceManager.GetString("GroupAdministratorsOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An group with id &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string GroupDoesntExistMessage {
            get {
                return ResourceManager.GetString("GroupDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An argument was invalid.  See the InvalidArgumentFault for details..
        /// </summary>
        internal static string InvalidArgumentFaultReason {
            get {
                return ResourceManager.GetString("InvalidArgumentFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        internal static string InvalidEmptyArgumentMessage {
            get {
                return ResourceManager.GetString("InvalidEmptyArgumentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group Id {0} is not valid..
        /// </summary>
        internal static string InvalidGroupId {
            get {
                return ResourceManager.GetString("InvalidGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user exists with the supplied user name or email address..
        /// </summary>
        internal static string InvalidUserNameOrEmailAddress {
            get {
                return ResourceManager.GetString("InvalidUserNameOrEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authorization failed.  See the NotAuthorizedFault for details..
        /// </summary>
        internal static string NotAuthorizedFaultReason {
            get {
                return ResourceManager.GetString("NotAuthorizedFaultReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0}.
        /// </summary>
        internal static string OnDateText {
            get {
                return ResourceManager.GetString("OnDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported service type..
        /// </summary>
        internal static string ServiceTypeNotSupportedMessage {
            get {
                return ResourceManager.GetString("ServiceTypeNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only system administrators can perform this action..
        /// </summary>
        internal static string SystemAdministratorsOnlyMessage {
            get {
                return ResourceManager.GetString("SystemAdministratorsOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type must be checking or savings account..
        /// </summary>
        internal static string TokenizationAccountTypeInvalid {
            get {
                return ResourceManager.GetString("TokenizationAccountTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 hours.
        /// </summary>
        internal static string TwentyFourHours {
            get {
                return ResourceManager.GetString("TwentyFourHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} is not authorized to perform the action..
        /// </summary>
        internal static string UnauthorizedExceptionMessage {
            get {
                return ResourceManager.GetString("UnauthorizedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either userName or emailAddress is required..
        /// </summary>
        internal static string UserNameOrEmailAddressRequired {
            get {
                return ResourceManager.GetString("UserNameOrEmailAddressRequired", resourceCulture);
            }
        }
    }
}
